export const items = [
    {
        id: 1,
        name: '카페 시온',
        category: '애가PASS',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 2,
        name: '드네이쳐',
        category: '여름물놀이',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 3,
        name: '괴정3동 작은도서관',
        category: '이번주핫플',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 4,
        name: '파티모먼트',
        category: '축제&공연',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 5,
        name: '프레리키즈카페',
        category: '축제&공연',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 6,
        name: '키즈몬',
        category: '애가PASS',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 7,
        name: '어린이작은도서관',
        category: '키즈숙박',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 8,
        name: '감천문화마을',
        category: '축제&공연',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 9,
        name: '비석문화마을',
        category: '키즈숙박',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
    {
        id: 10,
        name: '부산교육역사관',
        category: '애가PASS',
        thumbnail: 'https://via.placeholder.com/100',
        address: '강원특별자치도 속초시 대표항희망길 120',
        description: '상세설명입니다.',
        images: 'https://via.placeholder.com/150',
    },
];
