export const items = [
    {
        id: 1,
        name: '카페 시온',
        detail: 'Item Detail 1',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 2,
        name: '드네이쳐',
        detail: 'Item Detail 2',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 3,
        name: '괴정3동 작은도서관',
        detail: 'Item Detail 3',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 4,
        name: '파티모먼트',
        detail: 'Item Detail 4',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 5,
        name: '프레리키즈카페',
        detail: 'Item Detail 5',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 6,
        name: '키즈몬',
        detail: 'Item Detail 6',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 7,
        name: '어린이작은도서관',
        detail: 'Item Detail 7',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 8,
        name: '감천문화마을',
        detail: 'Item Detail 8',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 9,
        name: '비석문화마을',
        detail: 'Item Detail 9',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
    {
        id: 10,
        name: '부산교육역사관',
        detail: 'Item Detail 10',
        count: 1,
        imageUrl: 'https://via.placeholder.com/150',
    },
];
